services:

  db:
    image: postgres:17-alpine
    container_name: shop-db

    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop

    ports:
      - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db-init/02-data.sql:/docker-entrypoint-initdb.d/02-data.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop -d shop"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: shop-vlc-dio-api/dockerfile

    container_name: shop-api

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shop
      SPRING_PROFILES_ACTIVE: postgres

  web:
    build:
      context: .
      dockerfile: shop-vlc-dio-web/dockerfile

    container_name: shop-web

    ports:
      - "8080:8080"

    depends_on:
      db:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shop
      SPRING_PROFILES_ACTIVE: postgres

volumes:
  db-data: