
spring.application.name=shop-vlc-dio-api
server.port=8000

spring.profiles.active=h2

jwt.secret=Somos_mas_de_Colacao_que_de_te_para_ser_sinceros
jwt.access-token.expiration=3600000
jwt.refresh-token.expiration=86400000

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
shop.security.bcrypt.cost.factor=12







