
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=shop
spring.datasource.password=shop

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
