
spring.application.name=shop-vlc-dio-web


spring.profiles.active=postgres

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
shop.security.bcrypt.cost.factor=12
shop.validation.client-validation-enabled=false