
-- CREATE TYPE security_event_type AS ENUM ('ERROR', 'LOGIN', 'LOGOUT');

CREATE TABLE roles (
                       id VARCHAR(6) NOT NULL,
                       description VARCHAR(100),
                       PRIMARY KEY (id)
);

CREATE TABLE brand (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                       image VARCHAR(500),
                       name VARCHAR(150),
                       PRIMARY KEY (id),
                       CONSTRAINT UK_brand_name UNIQUE (name)
);

CREATE TABLE category (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                          description VARCHAR(2000) NOT NULL,
                          image VARCHAR(500),
                          name VARCHAR(100) NOT NULL,
                          PRIMARY KEY (id),
                          CONSTRAINT UK_category_name UNIQUE (name)
);

CREATE TABLE users (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                       birth_date DATE,
                       email VARCHAR(200) NOT NULL,
                       last_name VARCHAR(50) NOT NULL,
                       name VARCHAR(50) NOT NULL,
                       password VARCHAR(100) NOT NULL,
                       phone_number VARCHAR(200),
                       registration_date TIMESTAMP(6) NOT NULL,
                       username VARCHAR(50) NOT NULL,
                       PRIMARY KEY (id),
                       CONSTRAINT UK_user_email UNIQUE (email),
                       CONSTRAINT UK_user_phone UNIQUE (phone_number),
                       CONSTRAINT UK_user_username UNIQUE (username)
);

-- 3. Tablas con dependencias (Claves foráneas)
CREATE TABLE product (
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                         code VARCHAR(13) NOT NULL,
                         description VARCHAR(4000) NOT NULL,
                         discount INTEGER NOT NULL,
                         img VARCHAR(500),
                         name VARCHAR(200) NOT NULL,
                         price DOUBLE PRECISION NOT NULL,
                         stock INTEGER NOT NULL,
                         brand_id INTEGER NOT NULL,
                         PRIMARY KEY (id),
                         CONSTRAINT UK_product_code UNIQUE (code),
                         CONSTRAINT FK_product_brand FOREIGN KEY (brand_id) REFERENCES brand(id)
);

CREATE TABLE product_category (
                                  product_id INTEGER NOT NULL,
                                  category_id INTEGER NOT NULL,
                                  PRIMARY KEY (product_id, category_id),
                                  CONSTRAINT FK_pc_category FOREIGN KEY (category_id) REFERENCES category(id),
                                  CONSTRAINT FK_pc_product FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE user_role (
                           user_id INTEGER NOT NULL,
                           role_id VARCHAR(6) NOT NULL,
                           PRIMARY KEY (user_id, role_id),
                           CONSTRAINT FK_ur_role FOREIGN KEY (role_id) REFERENCES roles(id),
                           CONSTRAINT FK_ur_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE cart_item (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           units INTEGER NOT NULL,
                           updated_at TIMESTAMP(6) NOT NULL,
                           product_id INTEGER NOT NULL,
                           user_id INTEGER NOT NULL,
                           PRIMARY KEY (id),
                           CONSTRAINT UK_cart_product_user UNIQUE (product_id, user_id),
                           CONSTRAINT FK_cart_product FOREIGN KEY (product_id) REFERENCES product(id),
                           CONSTRAINT FK_cart_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE security_event (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                registration_date TIMESTAMP(6) NOT NULL,
                                type VARCHAR(10) NOT NULL,
                                username VARCHAR(30),
                                PRIMARY KEY (id)
);