name: Primer workflow

on:
  push:

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo "Hola desde GitHub Actions"

      - name: Mostrar directorio actual
        run: pwd

      - name: Listar contenido del directorio
        run: ls

      - name: Mostrar versión de Java
        run: java -version